### ISSUE TITLE
Bars aren't filling completely before rendering success

### ISSUE THREAD

**Issue by michaeljonathanblack** [lucleray/next-progressbar#4]
![image](https://user-images.githubusercontent.com/1099139/43174040-e9dcbe76-8f6c-11e8-8b4b-453c3d4e91e5.png)

This makes my heart sad. Not sure if it's an issue with next-progressbar or the webpackbar itself, but this is a good place to start.

**Comment by lucleray** [comment]
This is likely to be an issue related to webpackbar itself. 

I wonder if it's the expected behavior for webpackbar 🤔
