### ISSUE TITLE
How do i use this with "withCss"

### ISSUE THREAD

**Issue by capsulejj** [lucleray/next-progressbar#5]
Hi, I already have a 
"const withCSS = require('@zeit/next-css');"
in the config file.
So how can i use your library with this?
Thanks !

**Comment by lucleray** [comment]
You can combine next-plugins with function composition, like this :

```js
const withCss = require('@zeit/next-css')
const withProgressBar = require('next-progressbar')

module.exports = withProgressBar(withCss({
  // your custom configuration
}))
```
