### ISSUE TITLE
Error when building with Webpack3 in project ejected from create-react-app

### ISSUE THREAD

**Issue by shamas** [lucleray/next-progressbar#6]
> Creating an optimized production build...
> Failed to compile.
> 
> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
>  - configuration has an unknown property 'webpack'. These properties are valid:
>    object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
>    For typos: please correct them.
>    For loader options: webpack 2 no longer allows custom properties in configuration.

// Code implementing
let compiler = webpack(withProgressBar(config))
compiler.run((err, stats) => {

**Comment by lucleray** [comment]
This is a plugin for Next.js, not create-react-app. You need to use [webpackbar](https://github.com/nuxt/webpackbar) for what you want to do.
